services:
  - type: web
    name: todo-app
    env: docker
    buildCommand: docker build -t todo-app .
    startCommand: docker run -p $PORT:$PORT -e PORT=$PORT todo-app
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_NAME
        value: todo

databases:
  - name: todo-db
    databaseName: todo
    plan: free
    ipAllowList: [] # optional, allow connections from all IP addresses